#!/usr/bin/env python3

import os
import sys
import time
import subprocess
import common

my_dir = os.path.dirname(os.path.realpath(__file__))
my_name = os.path.basename(__file__)

TIMEOUT = 600

if __name__ == "__main__":
    pid = str(os.getpid())

    with open(common.pid_file(), 'w') as f:
        f.write(pid)
    # Let launcher know that I've successfully written the pid file
    print("D") # D for done
    sys.stdout.flush()

    time.sleep(TIMEOUT)
    with open(common.pid_file(), 'r') as f:
        newpid = f.read()
        if newpid == pid:
            cmd = [common.bloop_executable(), "ng-stop"]
            subprocess.run(cmd)
            os.unlink(common.pid_file())

