#!/usr/bin/env bash
# Daemon process to close the bloop server after a timeout
# Launching additional instances of this script will reset the timeout

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PID_FILE=".bloop_timeout.pid"
BLOOP_EXE=$DIR/../bin/bloop
TIMEOUT=10
PID=$$

echo $PID > $PID_FILE

# Become a proper daemon, close stdout and stderr
exec 1>&-
exec 2>&-
sleep $TIMEOUT

NEW_PID=`cat $PID_FILE`
if [ $NEW_PID -eq $PID ]; then
  $BLOOP_EXE ng-stop
  rm $PID_FILE
fi

