#!/usr/bin/env python3

import sys

if sys.version_info[0] < 3 or sys.version_info[1] < 5:
    print("This program requires Python version 3.5 or newer")
    sys.exit(1)

import os
import argparse
from lib import scalaplugin
from lib import common
from lib import logger

def get_parser():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
                                     description='Fetch Ivy Dependencies')
    parser.add_argument('--scala-dir', dest='scala_dir', metavar='DIR', required=True,
                        help='directory in which to install Scala',
                        type=common.is_existing_dir)
    parser.add_argument('--cache-dir', dest='cache_dir', metavar='DIR', required=True,
                        help='directory in which to cache ivy dependencies',
                        type=common.is_existing_dir)
    parser.add_argument('file', nargs='+', help='Ivy Dependencies JSON',
                        type=argparse.FileType('r'))
    logger.add_verbosity_arg(parser)
    return parser

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    scalaplugin.fetch_ivy_dependencies(args.file, args.scala_dir, args.cache_dir)
